package com.moon.myreadapp.mvvm.models.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig feedDaoConfig;
    private final DaoConfig articleDaoConfig;

    private final UserDao userDao;
    private final FeedDao feedDao;
    private final ArticleDao articleDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        feedDaoConfig = daoConfigMap.get(FeedDao.class).clone();
        feedDaoConfig.initIdentityScope(type);

        articleDaoConfig = daoConfigMap.get(ArticleDao.class).clone();
        articleDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        feedDao = new FeedDao(feedDaoConfig, this);
        articleDao = new ArticleDao(articleDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Feed.class, feedDao);
        registerDao(Article.class, articleDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        feedDaoConfig.getIdentityScope().clear();
        articleDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public FeedDao getFeedDao() {
        return feedDao;
    }

    public ArticleDao getArticleDao() {
        return articleDao;
    }

}
